### PR TITLE
VW e-up! support

### PR DESCRIPTION
**Pull request by markus-k**
This pull requests adds basic support for the Volkswagen e-up. I copied the eGolf/ID.3 component and made some adjustments. Mainly, the e-up uses 11-bit CAN and afaik doesn't have the inlet temperature command. 

I have tested this on my car and it seems to work so far. 

The car also seems to support reading the cumulative energy charged/discharged, which I haven't added yet. So there's still some work to do for full support.

### CODE REVIEW

**Comment by HabibA007** [comment]
Is there something new on this topic?

**Comment by cacula** [comment]
@markus-k i would like to build the version with eup support myself. could you please tell which Cordova and jdk version you used? thanks.

**Comment by b-reich** [comment]
> @markus-k i would like to build the version with eup support myself. could you please tell which Cordova and jdk version you used? thanks.

I build it for @markus-k 
I used Java-8 and Cordova Version 10.0.0

```
cd ~/EVNotify/app
 rollup --config rollup.config.js\n
 cordova build android
```

be sure your android sdk path is correct
```
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
```

**Comment by b-reich** [comment]
@cacula is this working for you?

**Comment by cacula** [comment]
@b-reich didn't have time yet. will report back asap

**Comment by cacula** [comment]
@b-reich well, i put client.js in the wrong folder ( as per contribution istructions ) - instead of app it needs to be in app/ww as you told me. works now. thank you very much for your support. very appreciated!
I would like to help adding the missing values like cumulative energy charged/discharged and 12V Battery Status. Is there any document/tutorial how to find the corresponding commands?

**Comment by b-reich** [comment]
@cacula u are welcome.
Checkout https://www.goingelectric.de/wiki/Liste-der-OBD2-Codes/

**Comment by HabibA007** [comment]
E-Up support would be great. Something new?

**Comment by GPlay97** [comment]
I was offline for a long time here. I'm really sorry for that. In the past few months I have worked on the new upcoming app generation v3 for EVNotify.

I will still merge this now, try to bring out a new update, if I am able to compile it. Will probably be the last v2 version, before v3 (which is currently in a new private repository) will be testable and public for you guys.

Thank you for the very good contribution and sorry again for not responding earlier.

**Review by GPlay97 — APPROVED** [review]

**Pull request merged**
